description: Project info
type: object
required: [id, name, department]
properties:
  id:
    type: number
    description: Project IDs must be unique
  name:
    type: string
    description: Project names must be unique
    minLength: 1
  description:
    type: string
  department:
    $ref: "../../swagger.yaml#/definitions/department"
  startedOn:
    type: string
    format: date
  endedOn:
    type: string
    format: date
  assigned:
    type: array
    minItems: 1
    items:
      type: string
      description: Usernames of employees assigned to the project
      minLength: 1
